### ISSUE TITLE
min zoom level not correctly handled in tiled map layers

### ISSUE THREAD

**Issue by claustres** [kalisio/kdk#126]
It appears that in some cases when zooming in/out quickly some features remain visible although the current zoom level is lower than the min zoom level. It probably appear when the data are currently fetched but not yet loaded and the user changes the zoom level.

**Comment by robinbourianes-frizko** [comment]
In the tiled mesh layer i handle this by storing the zoom level in the tile (https://github.com/kalisio/kdk/blob/master/map/client/leaflet/TiledMeshLayer.js#L191) and update visibility based on current zoom level (since some tile may complete loading while the user has changed zoom level).

I also listen to 'zoomstart' and 'zoomend' events : https://github.com/kalisio/kdk/blob/master/map/client/leaflet/TiledMeshLayer.js#L217
In 'zoomstart' i hide all tile stuff related to current zoom level, since we're about to change it, in 'zoomend' i only show tile data for the current zoom level.
I don't think you need the zoomstart and zoomend stuff though. I did this to fix the issue where mesh from multiple zoom level where overlapping and blending weirdly.

**Comment by claustres** [comment]
Great, adding a check on zoom level in `onTilLoad()` seems to fix some issues. However I think we also have another a problem with [this check](https://github.com/kalisio/kdk/blob/master/map/client/leaflet/TiledFeatureLayer.js#L40) when managing min/max zoom level. 

If we have a min zoom level at 13 and perform the following actions:
1. display the data at level 13
2. zoom back to 12
3. zoom in again at 13
Then nothing get displayed

 Indeed, the check will consider that the parent tile at level 12 is already loaded (although it contains no data at this zoom level), so that level 13 will not be requested again.

**Comment by claustres** [comment]
I wonder if we should also add a test about min/max zoom level in the `createTile()` method in addition to `onTilLoad()/onTileUnload()` to avoid any DOM elements "leak". Indeed it's not clear when the tile DOM element is added to the DOM by Leaflet.
