### ISSUE TITLE
Enhance e2e tests across the modules/apps

### ISSUE THREAD

**Issue by cnouguier** [kalisio/kdk#38]
* [ ] Study the possibility to share some of the page models in the related modules instead of copying-pasting into each application, test first by migrating some of the kApp page models into kCore
* [ ] Improve tests in kApp so that most of kCore UI components are covered, will probably require to integrate additional functionalities eg
  * collection management => create, edit, remove items in list and grid
  * form edition => custom form edition with all field types
  * account management => profile edition, password/email change, account removal

We should reuse some page models/tests from Akt'n'Map for this.

**Comment by leob** [comment]
I've checked if I could move the page models to kCore so that they can be shared, but unfortunately this does not seem to work - I'm getting an exception about selectors not working.

The reason might be that TestCafe uses a specially configured Babel compiler process (see https://github.com/DevExpress/testcafe/issues/2659#issuecomment-493095663 and also, more clearly, https://github.com/DevExpress/testcafe/issues/2654), and that probably does not work with JS files outside of the "test" directory which I import from somewhere under node_modules.

But, I saw this Github issue which explains a bit more clearly how the compilation process for TestCafe works:

https://github.com/DevExpress/testcafe/issues/2654

and they also suggest a workaround which I might try to implement:

https://github.com/DevExpress/testcafe/issues/2654#issuecomment-407571960

(the idea is that the files are pre-compiled before they're used by the tests - this is something we might set up as part of "npm run watch" within kCore)

**Comment by claustres** [comment]
We previously had a similar issue with quasar prior v1 and vue files coming from external modules that were not transpiled because it only took care of files under `/src`. We fixed that by automatically copy the files in the app dir before launching the build, if nothing else work we might do the same in this case ?

**Comment by leob** [comment]
Yes, if we copy the files from node_modules/kdk-core to kApp/test then it would work ... so that would mean we would need to add an extra step to the "cafe" command in package.json of kApp. If the other approach that I was looking at does not work then we can consider this.

**Comment by cnouguier** [comment]
Since we merge the modules, we can close this issue.
