### ISSUE TITLE
Organisation owner should see all groups

### ISSUE THREAD

**Issue by kazemar** [kalisio/kdk#450]
An organisation owner should see all groups : today if he's removed from a group, he won't see anymore this group.

**Comment by claustres** [comment]
Contrary to tags, which are visible by all members, groups have a notion of rights. Members that are not part of the group cannot interact with it by design. It can be viewed as a closed workspace only managed and accessible to group members.

If groups were "public" than there will not be any difference with tags and it will be useless.
